### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by Alexander-Morin** [PavlidisLab/TR_singlecell#1]
**General**
- [ ] slurm workflow
- [ ] Better organization of input data and output objects (mat+meta and aggregate matrix)
- [ ] Workflow needs to be more explicit about kept genes
- [ ] Keep kept but zero genes upfront (performance hit of NA check?) or add after cor and before final rank?
- [ ] Try sparse matrix correlation

**utils**
- [ ] aggregate functions finalized naming (if keeping all)
- [ ] aggregate functions doc spells out NA behavior
- [ ] binarized threshold aggregate
- [ ] min rank aggregate
- [ ] review use of transpose (and be explicit about incoming shape)
- [ ] test agg functions needs more (like checking symmetric)
- [ ] doc
